# Generated by Django 4.1.2 on 2022-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=200, null=True)),
                ('sciname', models.CharField(max_length=200, null=True)),
                ('genericname', models.CharField(max_length=200, null=True)),
                ('producttype', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(max_length=200, null=True)),
                ('otc', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('labeler', models.CharField(max_length=200, null=True)),
                ('ndcid', models.CharField(max_length=200, null=True)),
                ('pharmclass', models.CharField(default='Unknown', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('descriptionurl', models.URLField(null=True)),
                ('wordlist', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='corpus',
            name='medspecialty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='metadata',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='addedby',
            field=models.CharField(default='System', max_length=200),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='corpus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='safe',
            field=models.BooleanField(default=False),
        ),
    ]
