# Generated by Django 4.1.2 on 2022-12-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_medication_symptom_corpus_medspecialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='wordlist',
            field=models.TextField(),
        ),
    ]
