# Generated by Django 4.1.2 on 2022-12-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_alter_symptom_wordlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpus',
            old_name='date imported',
            new_name='import_date',
        ),
        migrations.RenameField(
            model_name='corpus',
            old_name='addedby',
            new_name='imported_by',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='brandname',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='sciname',
            new_name='compound_name',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='genericname',
            new_name='generic_name',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='ndcid',
            new_name='ndc_id',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='pharmclass',
            new_name='pharm_class',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='producttype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='descriptionurl',
            new_name='url',
        ),
    ]
