# Generated by Django 4.1.2 on 2022-12-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_rename_date imported_corpus_import_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='brand_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='compound_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='generic_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='labeler',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='ndc_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='pharm_class',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
