# Generated by Django 4.1.2 on 2022-12-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_alter_medication_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='brand_norm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='generic_norm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='labeler_norm',
            field=models.TextField(null=True),
        ),
    ]
