# Generated by Django 4.1.2 on 2022-12-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_medication_brand_norm_medication_generic_norm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='compound_norm',
            field=models.TextField(null=True),
        ),
    ]
