# Generated by Django 4.1.2 on 2022-12-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_medication_compound_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='brand_name',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='compound_name',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='generic_name',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='labeler',
            field=models.TextField(default='N/A'),
        ),
    ]
