# Generated by Django 4.1.2 on 2022-12-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_alter_medication_compound_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='corpus_norm',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='corpus',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
