# Generated by Django 4.1.2 on 2022-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_corpus_corpus_norm_alter_corpus_corpus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='title',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
    ]
