# Generated by Django 4.1.2 on 2022-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0013_alter_corpus_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='name_norm',
            field=models.TextField(null=True),
        ),
    ]
